### ISSUE TITLE
Run error

### ISSUE THREAD

**Issue by burnham** [EverCG/automotive-configurator#1]
Hi, thanks for your work, I just follow every thing in detail, but I get this message:
![image](https://user-images.githubusercontent.com/249632/193558753-b972b93b-dcab-4f85-a78b-759486218207.png)
Thanks in advance.

**Comment by rendercodeninja** [comment]
Hi Burnham,

I haven't checked in a Linux machine until now. But for the project, Windows is not a mandatory thing and should work fine linux systems too. 

I just tried the repo on Ubuntu 20.04.2 LTS (which I have) and it seems to work fine.

Here are my node, npm versions
<pre><font color="#4E9A06"><b>studio@Studio-Ubuntu</b></font>:<font color="#3465A4"><b>~</b></font>$ node -v &amp;&amp; npm -v
v14.16.1
8.19.2
</pre>

Here are the repo cloning and npm install logs

<pre><font color="#4E9A06"><b>studio@Studio-Ubuntu</b></font>:<font color="#3465A4"><b>~</b></font>$ git clone https://github.com/EverCG/automotive-configurator.git
Cloning into &apos;automotive-configurator&apos;...
remote: Enumerating objects: 108, done.
remote: Counting objects: 100% (3/3), done.
remote: Compressing objects: 100% (3/3), done.
remote: Total 108 (delta 0), reused 1 (delta 0), pack-reused 105
Receiving objects: 100% (108/108), 32.16 MiB | 2.92 MiB/s, done.
Resolving deltas: 100% (13/13), done.
<font color="#4E9A06"><b>studio@Studio-Ubuntu</b></font>:<font color="#3465A4"><b>~</b></font>$ cd automotive-configurator/
<font color="#4E9A06"><b>studio@Studio-Ubuntu</b></font>:<font color="#3465A4"><b>~/automotive-configurator</b></font>$ npm install
<span style="background-color:#2E3436"><font color="#D3D7CF">npm</font></span> <span style="background-color:#C4A000"><font color="#2E3436">WARN</font></span> <font color="#75507B">old lockfile</font> 
<span style="background-color:#2E3436"><font color="#D3D7CF">npm</font></span> <span style="background-color:#C4A000"><font color="#2E3436">WARN</font></span> <font color="#75507B">old lockfile</font> The package-lock.json file was created with an old version of npm,
<span style="background-color:#2E3436"><font color="#D3D7CF">npm</font></span> <span style="background-color:#C4A000"><font color="#2E3436">WARN</font></span> <font color="#75507B">old lockfile</font> so supplemental metadata must be fetched from the registry.
<span style="background-color:#2E3436"><font color="#D3D7CF">npm</font></span> <span style="background-color:#C4A000"><font color="#2E3436">WARN</font></span> <font color="#75507B">old lockfile</font> 
<span style="background-color:#2E3436"><font color="#D3D7CF">npm</font></span> <span style="background-color:#C4A000"><font color="#2E3436">WARN</font></span> <font color="#75507B">old lockfile</font> This is a one-time fix-up, please be patient...
<span style="background-color:#2E3436"><font color="#D3D7CF">npm</font></span> <span style="background-color:#C4A000"><font color="#2E3436">WARN</font></span> <font color="#75507B">old lockfile</font> 
<span style="background-color:#2E3436"><font color="#D3D7CF">npm</font></span> <span style="background-color:#C4A000"><font color="#2E3436">WARN</font></span> <font color="#75507B">deprecated</font> har-validator@5.1.5: this library is no longer supported
<span style="background-color:#2E3436"><font color="#D3D7CF">npm</font></span> <span style="background-color:#C4A000"><font color="#2E3436">WARN</font></span> <font color="#75507B">deprecated</font> querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
<span style="background-color:#2E3436"><font color="#D3D7CF">npm</font></span> <span style="background-color:#C4A000"><font color="#2E3436">WARN</font></span> <font color="#75507B">deprecated</font> uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
<span style="background-color:#2E3436"><font color="#D3D7CF">npm</font></span> <span style="background-color:#C4A000"><font color="#2E3436">WARN</font></span> <font color="#75507B">deprecated</font> request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142

added 500 packages, and audited 501 packages in 10s

51 packages are looking for funding
  run `npm fund` for details

<font color="#CC0000"><b>13</b></font> vulnerabilities (2 <font color="#C4A000"><b>moderate</b></font>, 8 <font color="#CC0000"><b>high</b></font>, 3 <font color="#75507B"><b>critical</b></font>)

To address issues that do not require attention, run:
  npm audit fix

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.
<font color="#4E9A06"><b>studio@Studio-Ubuntu</b></font>:<font color="#3465A4"><b>~/automotive-configurator</b></font>$</pre>

This is what I got when I run `npm run dev` after `npm install`. 

studio@Studio-Ubuntu:~/automotive-configurator$ npm run dev

> webgl-car-config@1.0.0 dev
> webpack serve

<i> [webpack-dev-server] Project is running at:
<i> [webpack-dev-server] Loopback: http://localhost:5000/
<i> [webpack-dev-server] On Your Network (IPv4): http://192.168.0.8:5000/
<i> [webpack-dev-server] Content not from webpack is served from '/home/studio/automotive-configurator/src/static' directory
<i> [webpack-dev-middleware] wait until bundle finished: /
assets by path assets/ 18.3 MiB
  assets by path assets/aventador/ 12.5 MiB
    assets by path assets/aventador/*.png 62.6 KiB
      asset assets/aventador/Render_Tyre_0A.png 32.9 KiB [emitted] [from: static/assets/aventador/Render_Tyre_0A.png] [copied]
      asset assets/aventador/Render_Tyre_0B.png 29.7 KiB [emitted] [from: static/assets/aventador/Render_Tyre_0B.png] [copied]
    asset assets/aventador/model.glb 12.4 MiB [emitted] [from: static/assets/aventador/model.glb] [copied]
    asset assets/aventador/meta.json 2.08 KiB [emitted] [from: static/assets/aventador/meta.json] [copied]
  asset assets/audio_track.mp3 3.08 MiB [emitted] [from: static/assets/audio_track.mp3] [copied]
  asset assets/exr/royal_esplanade_1k.exr 1.54 MiB [emitted] [from: static/assets/exr/royal_esplanade_1k.exr] [copied]
  asset assets/stage/model.glb 1.16 MiB [emitted] [from: static/assets/stage/model.glb] [copied]
asset js/app.build.js 2.4 MiB [emitted] (name: main)
asset css/style.css 4.03 KiB [emitted] [from: static/css/style.css] [copied]
asset images/github-mark-32px.png 1.67 KiB [emitted] [from: static/images/github-mark-32px.png] [copied]
asset index.html 1.27 KiB [emitted] [from: static/index.html] [copied]
runtime modules 27 KiB 13 modules
modules by path ../node_modules/ 2.06 MiB 32 modules
modules by path ./app/*.js 34.4 KiB
  ./app/app.js 6.4 KiB [built] [code generated]
  ./app/baseEngine.js 4.54 KiB [built] [code generated]
  ./app/config.js 368 bytes [built] [code generated]
  ./app/utilities.js 5.4 KiB [built] [code generated]
  ./app/cameraController.js 5.85 KiB [built] [code generated]
  ./app/inteface.js 7.3 KiB [built] [code generated]
  ./app/sceneManager.js 4.58 KiB [built] [code generated]

ERROR in ./app/sceneManager.js 2:0-67
Module not found: Error: Can't resolve 'three/examples/jsm/loaders/gltfloader' in '/home/studio/automotive-configurator/src/app'
resolve 'three/examples/jsm/loaders/gltfloader' in '/home/studio/automotive-configurator/src/app'
  Parsed request is a module
  using description file: /home/studio/automotive-configurator/package.json (relative path: ./src/app)
    Field 'browser' doesn't contain a valid alias configuration
    resolve as module
      /home/studio/automotive-configurator/src/app/node_modules doesn't exist or is not a directory
      /home/studio/automotive-configurator/src/node_modules doesn't exist or is not a directory
      looking for modules in /home/studio/automotive-configurator/node_modules
        existing directory /home/studio/automotive-configurator/node_modules/three
          using description file: /home/studio/automotive-configurator/node_modules/three/package.json (relative path: .)
            using description file: /home/studio/automotive-configurator/node_modules/three/examples/jsm/package.json (relative path: ./loaders/gltfloader)
              no extension
                Field 'browser' doesn't contain a valid alias configuration
                /home/studio/automotive-configurator/node_modules/three/examples/jsm/loaders/gltfloader doesn't exist
              .js
                Field 'browser' doesn't contain a valid alias configuration
                /home/studio/automotive-configurator/node_modules/three/examples/jsm/loaders/gltfloader.js doesn't exist
              .json
                Field 'browser' doesn't contain a valid alias configuration
                /home/studio/automotive-configurator/node_modules/three/examples/jsm/loaders/gltfloader.json doesn't exist
              .wasm
                Field 'browser' doesn't contain a valid alias configuration
                /home/studio/automotive-configurator/node_modules/three/examples/jsm/loaders/gltfloader.wasm doesn't exist
              as directory
                /home/studio/automotive-configurator/node_modules/three/examples/jsm/loaders/gltfloader doesn't exist
      /home/studio/node_modules doesn't exist or is not a directory
      /home/node_modules doesn't exist or is not a directory
      /node_modules doesn't exist or is not a directory
 @ ./app/app.js 16:0-46 43:8-25 62:35-62 64:37-66 80:8-30 89:12-40

webpack 5.53.0 compiled with 1 error in 2456 ms

I found an issue related to the new threeJS library version. Seems to be the GLTF loader library file name changed in new threeJS library version. 

![image](https://user-images.githubusercontent.com/16411386/193565511-1f635802-8aad-450f-bd56-25301fe06327.png)

The filename at the path for GLTF loader.
`node_modules/three/examples/jsm/loaders/gltfloader` 
is now 
`node_modules/three/examples/jsm/loaders/GLTFLoader`

So I changed (locally) in my `sceneManager.js`
```
02 import { GLTFLoader } from "three/examples/jsm/loaders/gltfloader";
```
to
```
02 import { GLTFLoader } from "three/examples/jsm/loaders/GLTFLoader";
```

And everything started working fine in my linux machine

![image](https://user-images.githubusercontent.com/16411386/193565748-14108dcd-f8dd-4c8d-b7e1-00fb55b3a3e8.png)

You need to have your graphics drivers installed (NVIDIA/AMD) for the webGL renderer otherwise there will be frame rate drops.

Hope this helps!

**Comment by burnham** [comment]
Thank you very much for your quick answer, I just also fin a solution and yes, I have the requirements. 
I have to say too: "Nice WORK".
Thanks again.
